# Generated by Django 6.0.1 on 2026-01-20 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurantes", "0008_restaurante_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impresora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_conexion",
                    models.CharField(
                        choices=[
                            ("usb", "USB"),
                            ("network", "Red/Ethernet"),
                            ("serial", "Serial"),
                            ("file", "Archivo (depuración)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("configuracion", models.JSONField(blank=True, default=dict)),
                ("ubicacion", models.CharField(blank=True, max_length=100)),
                ("es_termica", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impresoras",
                        to="restaurantes.restaurante",
                    ),
                ),
            ],
            options={
                "ordering": ("nombre",),
                "unique_together": {("restaurante", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ConfigImpresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("factura", "Factura"),
                            ("nota_credito", "Nota de Crédito"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=120)),
                ("encabezado", models.TextField(blank=True)),
                ("pie_pagina", models.TextField(blank=True)),
                (
                    "copias",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("opciones", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_impresion",
                        to="restaurantes.restaurante",
                    ),
                ),
                (
                    "impresora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones",
                        to="impresion.impresora",
                    ),
                ),
            ],
            options={
                "ordering": ("tipo_comprobante",),
                "unique_together": {("restaurante", "tipo_comprobante")},
            },
        ),
    ]
