# Generated by Django 6.0 on 2026-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="limi_cajas",
            field=models.IntegerField(default=1),
        ),
    ]
