# Generated by Django 6.0.1 on 2026-06-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_planes_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mercadopago_plan_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cancelar_al_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('trialing', 'Periodo de prueba'), ('pending', 'Pendiente'), ('authorized', 'Autorizada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Vencida')], default='trialing', max_length=30),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='proveedor_suscripcion_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=20)),
                ('proveedor_pago_id', models.CharField(max_length=255, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
