# Generated by Django 6.0.1 on 2026-06-19 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0004_plan_mercadopago_plan_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="limi_cajas",
            new_name="limite_cajas",
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="plan_pendiente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="suscripciones.plan",
            ),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="usuario_principal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suscripcion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
