# Generated by Django 6.0.1 on 2026-06-19 17:51

from django.db import migrations

def migrar_datos(apps, schema_editor):
    Restaurante = apps.get_model("restaurantes", "Restaurante")
    Suscripcion = apps.get_model("suscripciones", "Suscripcion")
    Pago = apps.get_model("suscripciones", "Pago")

    propietarios = Restaurante.objects.values_list(
        "propietario_id", flat=True
    ).distinct()

    for propietario_id in propietarios:
        restaurantes = Restaurante.objects.filter(
            propietario_id=propietario_id
        ).order_by("created_at", "id")

        matriz = restaurantes.first()
        if not matriz:
            continue

        restaurantes.update(es_matriz=False)
        matriz.es_matriz = True
        matriz.save(update_fields=["es_matriz"])

        suscripciones = Suscripcion.objects.filter(
            restaurante__propietario_id=propietario_id
        ).order_by("id")

        principal = suscripciones.filter(restaurante=matriz).first()
        if not principal:
            principal = suscripciones.first()

        if not principal:
            continue

        principal.usuario_principal_id = propietario_id
        principal.save(update_fields=["usuario_principal"])

        for duplicada in suscripciones.exclude(id=principal.id):
            Pago.objects.filter(suscripcion=duplicada).update(
                suscripcion=principal
            )
            duplicada.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0005_rename_limi_cajas_plan_limite_cajas_and_more"),
        ("restaurantes", "0009_restaurante_es_matriz"),
    ]

    operations = [
        migrations.RunPython(
            migrar_datos,
            migrations.RunPython.noop,
        ),
    ]
