# Generated by Django 6.0.1 on 2026-09-04 09:31

from django.db import migrations, models


def configurar_limites(apps, schema_editor):
    Plan = apps.get_model('suscripciones', 'Plan')
    limites_por_plan = {
        'basico': (3, 3),
        'profesional': (8, 8),
        'premium': (20, 20),
    }
    for plan in Plan.objects.all():
        limites = limites_por_plan.get(plan.nombre.casefold())
        if limites:
            plan.limite_areas, plan.limite_estaciones = limites
            plan.save(update_fields=['limite_areas', 'limite_estaciones'])


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0007_suscripcion_por_usuario_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limite_areas',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='limite_estaciones',
            field=models.IntegerField(default=3),
        ),
        migrations.RunPython(configurar_limites, migrations.RunPython.noop),
    ]
