# Generated by Django 6.0 on 2026-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="apellidoM",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="apellidoP",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
