# Generated by Django 6.0.1 on 2026-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_usuario_google_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email_verificado",
            field=models.BooleanField(default=False),
        ),
    ]
