# Generated by Django 6.0.1 on 2026-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_verificar_usuarios_existentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email_verificado",
            field=models.BooleanField(default=False),
        ),
    ]
