# Generated by Django 6.0 on 2026-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_mesa_pedido_pedidodetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesa",
            name="capacidad",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="mesa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("ocupada", "Ocupada"),
                    ("reservada", "Reservada"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierto", "Abierto"),
                    ("cerrado", "Cerrado"),
                    ("cancelado", "Cancelado"),
                ],
                default="abierto",
                max_length=20,
            ),
        ),
    ]
