# Generated by Django 6.0 on 2026-01-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_mesa_capacidad_mesa_estado_alter_pedido_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="Usuario",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="fecha",
        ),
        migrations.AddField(
            model_name="venta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pagada", "Pagada"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.mesa",
            ),
        ),
        migrations.AlterField(
            model_name="ventadetalle",
            name="cantidad",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
