# Generated by Django 6.0 on 2026-01-08 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_remove_venta_usuario_remove_venta_fecha_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="mesa",
        ),
        migrations.RemoveField(
            model_name="ventadetalle",
            name="fecha",
        ),
        migrations.AddField(
            model_name="venta",
            name="pedido",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Comensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ventas.mesa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ventadetalle",
            name="comensal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.comensal",
            ),
        ),
    ]
