# Generated by Django 6.0 on 2026-01-08 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_remove_venta_mesa_remove_ventadetalle_fecha_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="mesero",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"usuariorestaurante__rol": "mesero"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
