# Generated by Django 6.0 on 2026-01-08 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_pedido_mesero"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidodetalle",
            name="comensal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.comensal",
            ),
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="enviado_cocina",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
