# Generated by Django 6.0 on 2026-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_pedidodetalle_comensal_pedidodetalle_enviado_cocina_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidodetalle",
            name="observaciones",
            field=models.TextField(blank=True, default=""),
        ),
    ]
