# Generated by Django 6.0.1 on 2026-01-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0008_pedidodetalle_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventadetalle",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
            ),
        ),
    ]
