# Generated by Django 6.0.1 on 2026-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0010_venta_caja"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidodetalle",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
    ]
