# Generated by Django 6.0 on 2026-01-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0011_pedidodetalle_cancelado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidodetalle",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="pagado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidodetalle",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_pedido",
                to="ventas.venta",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="ventas.pedido",
            ),
        ),
    ]
