# Generated by Django 6.0.1 on 2026-09-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0011_areaservicio'),
        ('ventas', '0012_pedidodetalle_pagado_pedidodetalle_pagado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='restaurantes.areaservicio'),
        ),
    ]
