# Generated by Django 6.0 on 2025-12-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.categoria",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
        ),
    ]
