# Generated by Django 6.0 on 2026-01-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="productos.categoria",
            ),
        ),
    ]
