# Generated by Django 6.0 on 2026-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_categoria_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio_por_unidad",
            field=models.CharField(
                choices=[
                    ("unidad", "Unidad"),
                    ("kilogramo", "Kilogramo"),
                    ("gramo", "Gramo"),
                    ("litro", "Litro"),
                    ("mililitro", "Mililitro"),
                    ("porcion", "Porción"),
                ],
                default="unidad",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
