# Generated by Django 6.0 on 2026-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_producto_precio_por_unidad_alter_producto_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="url_imagen",
            field=models.URLField(blank=True),
        ),
    ]
