# Generated by Django 6.0.1 on 2026-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_categoria_url_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
