# Generated by Django 6.0.1 on 2026-08-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_codigo_barras'),
        ('restaurantes', '0010_estacion_usuariorestaurante_estaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='restaurantes.estacion'),
        ),
    ]
