# Generated by Django 6.0 on 2025-12-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurantes", "0003_restaurante_ciudad_restaurante_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_moneda", models.CharField(default="USD", max_length=10)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurantes.restaurante",
                    ),
                ),
            ],
        ),
    ]
