# Generated by Django 6.0 on 2025-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracion",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
