# Generated by Django 6.0 on 2025-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0002_configuracion_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracion",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
