# Generated by Django 6.0 on 2025-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("monto_inicial", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "monto_final",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
    ]
