# Generated by Django 6.0 on 2025-12-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caja", "0001_initial"),
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caja",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
        ),
    ]
