# Generated by Django 6.0.1 on 2026-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0004_caja_totales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocaja",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("salida", "Salida"),
                    ("ajuste", "Ajuste"),
                ],
                max_length=10,
            ),
        ),
    ]
