# Generated by Django 6.0 on 2025-12-26 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurantes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usuariorestaurante",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="usuariorestaurante",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
