# Generated by Django 6.0 on 2025-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="ciudad",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="estado",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="sitio_web",
            field=models.URLField(blank=True, null=True),
        ),
    ]
