# Generated by Django 6.0 on 2026-01-08 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0003_restaurante_ciudad_restaurante_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariorestaurante",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("cajero", "Cajero"),
                    ("mesero", "Mesero"),
                    ("cocinero", "Cocinero"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usuariorestaurante",
            unique_together={("usuario", "restaurante")},
        ),
    ]
