# Generated by Django 6.0 on 2026-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0004_alter_usuariorestaurante_rol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="usuariorestaurante",
            name="permisos",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios_restaurante",
                to="restaurantes.permiso",
            ),
        ),
    ]
