# Generated by Django 6.0 on 2026-01-09 16:40

from django.db import migrations


def crear_permisos_iniciales(apps, schema_editor):
    Permiso = apps.get_model("restaurantes", "Permiso")
    
    CHOICES = [
        ('todos_los_permisos', 'Todos los permisos'),
        ('ver_productos', 'Ver productos'),
        ('crear_productos', 'Crear productos'),
        ('editar_productos', 'Editar productos'),
        ('eliminar_productos', 'Eliminar productos'),
        ('ver_historial_ventas', 'Ver historial de ventas'),
        ('crear_ventas', 'Crear ventas'),
        ('ver_inventario', 'Ver inventario'),
        ('editar_inventario', 'Editar inventario'),
        ('ver_reportes', 'Ver reportes'),
        ('exportar_reportes', 'Exportar reportes'),
        ('administrar_usuarios', 'Administrar usuarios'),
        ('crear_pedidos', 'Crear pedidos'),
        ('ver_pedidos', 'Ver pedidos'),
        ('editar_pedidos', 'Editar pedidos'),
        ('ver_ordenes_cocina', 'Ver órdenes de cocina'),
        ('actualizar_estado_ordenes', 'Actualizar estado de órdenes'),
    ]

    for codigo, descripcion in CHOICES:
        Permiso.objects.get_or_create(
            codigo=codigo, 
            defaults={'descripcion': descripcion}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0005_permiso_usuariorestaurante_permisos"),
    ]

    operations = [
        migrations.RunPython(crear_permisos_iniciales),
    ]
