# Generated by Django 6.0.1 on 2026-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0006_poblar_permisos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariorestaurante",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("cajero", "Cajero"),
                    ("mesero", "Mesero"),
                    ("cocinero", "Cocinero"),
                    ("gerente", "Gerente"),
                ],
                max_length=10,
            ),
        ),
    ]
