# Generated by Django 6.0.1 on 2026-01-16 21:11

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def generate_unique_slug(existing_slugs, base_slug):
    if base_slug:
        slug_candidate = base_slug
        counter = 1
        while slug_candidate in existing_slugs:
            slug_candidate = f"{base_slug}-{counter}"
            counter += 1
    else:
        slug_candidate = f'restaurante-{uuid.uuid4().hex[:8]}'
        while slug_candidate in existing_slugs:
            slug_candidate = f'restaurante-{uuid.uuid4().hex[:8]}'

    existing_slugs.add(slug_candidate)
    return slug_candidate


def populate_slugs(apps, schema_editor):
    Restaurante = apps.get_model('restaurantes', 'Restaurante')
    existing_slugs = set(
        Restaurante.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True)
    )

    for restaurante in Restaurante.objects.all():
        if restaurante.slug:
            existing_slugs.add(restaurante.slug)
            continue

        base_slug = slugify(restaurante.nombre or '')
        restaurante.slug = generate_unique_slug(existing_slugs, base_slug)
        restaurante.save(update_fields=['slug'])


def remove_slugs(apps, schema_editor):
    Restaurante = apps.get_model('restaurantes', 'Restaurante')
    Restaurante.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0007_alter_usuariorestaurante_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identificador único para la URL del restaurante",
                max_length=120,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_slugs, reverse_code=remove_slugs),
    ]
