# Generated by Django 6.0.1 on 2026-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0008_restaurante_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="es_matriz",
            field=models.BooleanField(default=False),
        ),
    ]
