# Generated by Django 6.0.1 on 2026-08-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0009_restaurante_es_matriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='restaurantes.restaurante')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuariorestaurante',
            name='estaciones',
            field=models.ManyToManyField(blank=True, related_name='usuarios_restaurante', to='restaurantes.estacion'),
        ),
        migrations.AddConstraint(
            model_name='estacion',
            constraint=models.UniqueConstraint(fields=('restaurante', 'nombre'), name='estacion_nombre_unico_por_restaurante'),
        ),
    ]
