# Generated by Django 6.0.1 on 2026-09-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0010_estacion_usuariorestaurante_estaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_servicio', to='restaurantes.restaurante')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('restaurante', 'nombre'), name='area_servicio_nombre_unico_por_restaurante')],
            },
        ),
    ]
